"""Simulated NK landscapes + four sequence-to-fitness models + a greedy design step.
Usage: python method/run.py --system "Pairwise ridge" --task L15_A4_K2 --seed 0 --out m.json [--n_train 1000]
All landscapes are simulated (random-neighbourhood NK, hashed lookup tables)."""
import argparse, json, os, re, time
import numpy as np

M64 = np.uint64(0xFFFFFFFFFFFFFFFF)


def splitmix(z):
    z = (z + np.uint64(0x9E3779B97F4A7C15))
    z = (z ^ (z >> np.uint64(30))) * np.uint64(0xBF58476D1CE4E5B9)
    z = (z ^ (z >> np.uint64(27))) * np.uint64(0x94D049BB133111EB)
    return z ^ (z >> np.uint64(31))


class NK:
    """f(x) = (1/L) sum_i T_i(x_i, x_{nbrs(i)}), T_i entries iid U(0,1) generated by a hash."""
    def __init__(self, L, A, K, seed):
        self.L, self.A, self.K, self.seed = L, A, K, seed
        rng = np.random.default_rng(10_000 + seed)
        self.nbrs = np.array([rng.choice([j for j in range(L) if j != i], K, replace=False) for i in range(L)]).reshape(L, K)
        self.salt = np.uint64(splitmix(np.array([seed * 7919 + L * 131 + A * 17 + K], dtype=np.uint64))[0])

    def fitness(self, X):
        X = np.asarray(X, dtype=np.int64)
        tot = np.zeros(len(X))
        for i in range(self.L):
            idx = X[:, i].copy()
            for j in self.nbrs[i]:
                idx = idx * self.A + X[:, j]
            z = splitmix(idx.astype(np.uint64) + (np.uint64(i + 1) << np.uint64(40)) + self.salt)
            tot += (z >> np.uint64(11)).astype(np.float64) / float(2 ** 53)
        return tot / self.L

    def edges(self):  # pairs co-occurring in some neighbourhood {i} U nbrs(i)
        E = set()
        for i in range(self.L):
            s = sorted([i] + list(self.nbrs[i]))
            E |= {(a, b) for a in s for b in s if a < b}
        return sorted(E)


def onehot(X, A):
    N, L = X.shape
    O = np.zeros((N, L * A), dtype=np.float32)
    O[np.arange(N)[:, None], np.arange(L)[None, :] * A + X] = 1
    return O


# ---------------- ridge models in dual form ----------------
# Pairwise features: all products of one-hot indicators at two distinct sites. Their inner product is C(m,2),
# m = number of identical sites, so the kernel is exact, no feature matrix is built.
def kern(Xa, Xb, A, kind, r, edges=None):
    m = onehot(Xa, A) @ onehot(Xb, A).T
    if kind == "additive":
        return m
    if kind == "pairwise":
        return m + r * m * (m - 1) / 2
    if kind == "oracle":
        Ke = np.zeros_like(m)
        for (i, j) in edges:
            pa = Xa[:, i] * A + Xa[:, j]; pb = Xb[:, i] * A + Xb[:, j]
            Ke += (pa[:, None] == pb[None, :])
        return m + r * Ke
    raise ValueError(kind)


def spearman(a, b):
    from scipy.stats import spearmanr
    return float(spearmanr(a, b)[0])


class Ridge:
    def __init__(self, kind, A, fix_r=False, edges=None):
        self.kind, self.A, self.fix_r, self.edges = kind, A, fix_r, edges

    def _solve(self, Ktr, y, lam):
        return np.linalg.solve(Ktr + lam * np.eye(len(y)), y)

    def fit(self, X, y):
        lams = [0.01, 0.1, 1, 10, 100, 1000]
        rs = [1.0] if (self.kind == "additive" or self.fix_r) else [0.03, 0.1, 0.3, 1.0]
        n = len(X); p = np.random.default_rng(0).permutation(n); nv = n // 5
        va, tr = p[:nv], p[nv:]
        best = (-9, None)
        for r in rs:
            Kfull = kern(X, X, self.A, self.kind, r, self.edges).astype(np.float64)
            for lam in lams:  # tuning grid: len(lams)*len(rs) configs, scored by Spearman on 20% of the training set
                yt = y[tr] - y[tr].mean()
                a = self._solve(Kfull[np.ix_(tr, tr)], yt, lam)
                s = spearman(Kfull[np.ix_(va, tr)] @ a, y[va])
                if s > best[0]: best = (s, (r, lam))
        self.r, self.lam = best[1]
        self.X = X; self.mu = y.mean()
        Kfull = kern(X, X, self.A, self.kind, self.r, self.edges).astype(np.float64)
        self.alpha = self._solve(Kfull, y - self.mu, self.lam)
        return self

    def predict(self, Xq):
        return kern(Xq, self.X, self.A, self.kind, self.r, self.edges) @ self.alpha + self.mu


# ---------------- neural models ----------------
class Net:
    def __init__(self, arch, L, A, seed):
        self.arch, self.L, self.A, self.seed = arch, L, A, seed

    def _make(self):
        import torch.nn as nn
        L, A = self.L, self.A
        if self.arch == "mlp":
            return nn.Sequential(nn.Flatten(), nn.Linear(L * A, 128), nn.ReLU(), nn.Linear(128, 64), nn.ReLU(), nn.Linear(64, 1))
        return nn.Sequential(nn.Conv1d(A, 32, 5, padding=2), nn.ReLU(), nn.Flatten(),
                             nn.Linear(32 * L, 64), nn.ReLU(), nn.Linear(64, 1))

    def _in(self, X):
        import torch
        O = torch.tensor(onehot(X, self.A))
        return O.view(len(X), self.L, self.A).transpose(1, 2).contiguous() if self.arch == "cnn" else O

    def fit(self, X, y):
        import torch, copy
        torch.manual_seed(self.seed)
        self.mu, self.sd = y.mean(), y.std()
        Y = torch.tensor((y - self.mu) / self.sd, dtype=torch.float32)
        I = self._in(X)
        n = len(X); p = torch.randperm(n, generator=torch.Generator().manual_seed(self.seed))
        nv = int(0.15 * n); va, tr = p[:nv], p[nv:]
        best = (1e9, None, None)
        for wd in [1e-3, 1e-1]:  # tuning grid for weight decay, scored by validation MSE (15% of train)
            net = self._make()
            opt = torch.optim.AdamW(net.parameters(), lr=2e-3, weight_decay=wd)
            bl, bs, bad = 1e9, None, 0
            for ep in range(300):
                net.train()
                perm = tr[torch.randperm(len(tr))]
                for k in range(0, len(perm), 64):
                    b = perm[k:k + 64]
                    opt.zero_grad(); loss = ((net(I[b]).squeeze(1) - Y[b]) ** 2).mean(); loss.backward(); opt.step()
                net.eval()
                with torch.no_grad(): vl = ((net(I[va]).squeeze(1) - Y[va]) ** 2).mean().item()
                if vl < bl - 1e-5: bl, bs, bad = vl, copy.deepcopy(net.state_dict()), 0
                else:
                    bad += 1
                    if bad >= 25: break
            if bl < best[0]: best = (bl, bs, wd)
        self.net = self._make(); self.net.load_state_dict(best[1]); self.net.eval(); self.wd = best[2]
        return self

    def predict(self, Xq):
        import torch
        with torch.no_grad(): return self.net(self._in(Xq)).squeeze(1).numpy() * self.sd + self.mu


class RandomScorer:
    def __init__(self, seed): self.rng = np.random.default_rng(seed + 99)
    def fit(self, X, y): return self
    def predict(self, Xq): return self.rng.normal(size=len(Xq))


def single_mutants(x, A):
    L = len(x); out = []
    for i in range(L):
        for a in range(A):
            if a != x[i]:
                z = x.copy(); z[i] = a; out.append(z)
    return np.array(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--system", required=True); ap.add_argument("--task", required=True)
    ap.add_argument("--seed", type=int, default=0); ap.add_argument("--out", required=True)
    ap.add_argument("--n_train", type=int, default=1000); ap.add_argument("--n_test", type=int, default=5000)
    ap.add_argument("--top_b", type=int, default=10)
    a = ap.parse_args()
    L, A, K = map(int, re.match(r"L(\d+)_A(\d+)_K(\d+)", a.task).groups())
    os.environ.setdefault("OMP_NUM_THREADS", "2")
    print("config", vars(a), flush=True)
    land = NK(L, A, K, a.seed)
    rng = np.random.default_rng(a.seed)  # data seed shared by all systems for (task, seed)
    Xall = rng.integers(0, A, size=(a.n_train + a.n_test, L))
    yall = land.fitness(Xall)
    Xtr, ytr, Xte, yte = Xall[:a.n_train], yall[:a.n_train], Xall[a.n_train:], yall[a.n_train:]
    s = a.system
    t0 = time.time()
    if s == "Additive ridge": mdl = Ridge("additive", A)
    elif s == "Pairwise ridge": mdl = Ridge("pairwise", A)
    elif s == "Pairwise ridge (r fixed)": mdl = Ridge("pairwise", A, fix_r=True)
    elif s == "Pairwise ridge (oracle graph)": mdl = Ridge("oracle", A, edges=land.edges())
    elif s == "CNN" or s == "MLP":
        import torch; torch.set_num_threads(2); mdl = Net(s.lower(), L, A, a.seed)
    elif s == "Random": mdl = RandomScorer(a.seed)
    else: raise SystemExit("unknown system " + s)
    mdl.fit(Xtr, ytr)
    fit_s = time.time() - t0
    rho = spearman(mdl.predict(Xte), yte)
    # greedy design step: best measured training sequence is the parent; model ranks all single mutants; top-b proposed
    pi = int(np.argmax(ytr)); parent, fp = Xtr[pi], ytr[pi]
    C = single_mutants(parent, A); fc = land.fitness(C)
    prop = np.argsort(-mdl.predict(C), kind="stable")[:a.top_b]
    m = {"spearman": rho, "design_hit": float(np.mean(fc[prop] > fp)),
         "design_gain": float((fc[prop].max() - fp) / yte.std()),
         "frac_mutants_better": float(np.mean(fc > fp)), "fit_seconds": fit_s}
    for k in ("r", "lam", "wd"):
        if hasattr(mdl, k): m["hp_" + k] = float(getattr(mdl, k))
    print("metrics", m)
    json.dump(m, open(a.out, "w"))


if __name__ == "__main__":
    main()
